#!/bin/bash
# create-token.sh - 辅助创建 Token 的提示

echo "=== GitHub Token 创建助手 ==="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 打开: https://github.com/settings/tokens?type=beta"
echo "2. 点击 'Generate new token'"
echo "3. 填写:"
echo "   - Token name: upload-helper-$(date +%Y%m%d)"
echo "   - Expiration: Custom → $(date -v+1H '+%Y-%m-%d %H:%M') (1小时后)"
echo "   - Repository: 选择你的仓库"
echo "   - Permissions: Contents (Read and Write)"
echo "4. 点击 Generate"
echo "5. 复制 Token（只显示一次！）"
echo ""
echo "Token 格式: ghp_xxxxxxxxxxxxxxxxxxxx"
echo ""
echo "⚠️  安全提醒:"
echo "   - Token 1小时后自动失效"
echo "   - 只给信任的人"
echo "   - 用完立即删除"
